# Generated by Django 4.0 on 2024-04-11 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertask',
            old_name='task',
            new_name='kia',
        ),
    ]
